/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kevinschaeffer' at '5/4/14 12:39 AM' with Gradle 1.10
 *
 * @author kevinschaeffer, @date 5/4/14 12:39 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
